# Generated by Django 5.2.3 on 2025-06-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.CharField()),
                ('city', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=11)),
            ],
        ),
    ]
