# Generated by Django 3.1.12 on 2025-08-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_form_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
